// <auto-generated />
using FootballLeagueFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballLeagueFinder.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20220628161238_AddPlayersSeedToDatabase")]
    partial class AddPlayersSeedToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FootballLeagueFinder.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The West Kent League, is a football competition based in Kent, England. The league has seven senior divisions – a Premier Division, Division One East and West, Division Two East and West and Division Three East and West. It sits below the Southern Counties East League Division One (step 6 of the National League System)  ",
                            Location = "Kent",
                            Name = "West Kent League",
                            Photo = "https://www.pngkey.com/png/full/233-2332677_ega-png.png"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The East Kent League, is a football competition based in Kent, England. The league has seven senior divisions – a Premier Division, Division One East and West, Division Two East and West and Division Three East and West. It sits below the Southern Counties East League Division One (step 6 of the National League System)",
                            Location = "Kent",
                            Name = "East Kent League",
                            Photo = "https://www.pngkey.com/png/full/233-2332677_ega-png.png"
                        });
                });

            modelBuilder.Entity("FootballLeagueFinder.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ShirtNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jim",
                            LastName = "Jones",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 0,
                            ShirtNumber = "1",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Dave",
                            LastName = "Digby",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "2",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Simon",
                            LastName = "Jeffries",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "3",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Les",
                            LastName = "Formby",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "4",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Jim",
                            LastName = "Jones",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "5",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Albert",
                            LastName = "Albert",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "6",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Mitch",
                            LastName = "Walker",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "7",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Dave",
                            LastName = "Jones",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "8",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Richard",
                            LastName = "Smith",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "9",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Fred",
                            LastName = "Astaire",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "10",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Jim",
                            LastName = "Jones",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "11",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Cedric",
                            LastName = "Pinkerton",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 0,
                            ShirtNumber = "1",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Rupert",
                            LastName = "Bear",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "2",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Calvin",
                            LastName = "Blackberry",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "3",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Dean",
                            LastName = "Cheese",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "4",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Peter",
                            LastName = "Kadiri",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "5",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Scott",
                            LastName = "Dobson",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "6",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Keith",
                            LastName = "Fry",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "7",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Paul",
                            LastName = "Perry",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "8",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Sal",
                            LastName = "Silver",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "9",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Del",
                            LastName = "Gold",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "10",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Paul",
                            LastName = "Fry",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "11",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Eric",
                            LastName = "Erikson",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 0,
                            ShirtNumber = "1",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Claus",
                            LastName = "Jensen",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "2",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Steve",
                            LastName = "Brown",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "3",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Clive",
                            LastName = "Fink",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "4",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Ted",
                            LastName = "Smith",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "5",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Phil",
                            LastName = "Smith",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "6",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Jack",
                            LastName = "Jones",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "7",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Tony",
                            LastName = "Toblerone",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "8",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Sid",
                            LastName = "Kitkat",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "9",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Arnold",
                            LastName = "Gates",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "10",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Simon",
                            LastName = "Finch",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "11",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Tony",
                            LastName = "Montana",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 0,
                            ShirtNumber = "1",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Oz",
                            LastName = "Floss",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "2",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Si",
                            LastName = "Brown",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "3",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Keith",
                            LastName = "Beef",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "4",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Morgan",
                            LastName = "Telford",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "5",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Caz",
                            LastName = "Log",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "6",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Richard",
                            LastName = "Richardson",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "7",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Ken",
                            LastName = "Bruce",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "8",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Ray",
                            LastName = "Light",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "9",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Jason",
                            LastName = "Gates",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "10",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Simon",
                            LastName = "Finch",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "11",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Alex",
                            LastName = "Cod",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 0,
                            ShirtNumber = "1",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "John",
                            LastName = "Phillips",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "2",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Barry",
                            LastName = "Brown",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "3",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Mason",
                            LastName = "Fred",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "4",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Eric",
                            LastName = "Gonzo",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "5",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Les",
                            LastName = "Wood",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "6",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Alfie",
                            LastName = "Gooch",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "7",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Ron",
                            LastName = "Bonne",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "8",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Malcolm",
                            LastName = "Lightfoot",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "9",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Terry",
                            LastName = "Ronford",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "10",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Tim",
                            LastName = "Docherty",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "11",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Paul",
                            LastName = "Derk",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 0,
                            ShirtNumber = "1",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Colin",
                            LastName = "Clarke",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "2",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Barnie",
                            LastName = "Rubble",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "3",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Len",
                            LastName = "Fredson",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "4",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Igor",
                            LastName = "Vasalivitch",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 1,
                            ShirtNumber = "5",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Gordon",
                            LastName = "Smith",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "6",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Cuthbert",
                            LastName = "Dibble",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "7",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Eldridge",
                            LastName = "Coolerson",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "8",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Zack",
                            LastName = "Pow",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 2,
                            ShirtNumber = "9",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Ben",
                            LastName = "Boom",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "10",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Sid",
                            LastName = "Fortesque",
                            Photo = "http://shackmanlab.org/wp-content/uploads/2013/07/person-placeholder.jpg",
                            Position = 3,
                            ShirtNumber = "11",
                            TeamId = 6
                        });
                });

            modelBuilder.Entity("FootballLeagueFinder.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 1,
                            Manager = "Sid Bananas",
                            Name = "West Kent United",
                            Photo = "http://www.jennybeaumont.com/wp-content/uploads/2015/03/placeholder.gif"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 1,
                            Manager = "Dave Turnip",
                            Name = "Jongo Town",
                            Photo = "http://www.jennybeaumont.com/wp-content/uploads/2015/03/placeholder.gif"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 1,
                            Manager = "Jay Apple",
                            Name = "Dunkirk Athletic",
                            Photo = "http://www.jennybeaumont.com/wp-content/uploads/2015/03/placeholder.gif"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 2,
                            Manager = "Fred Grape",
                            Name = "Dels Dynamos",
                            Photo = "http://www.jennybeaumont.com/wp-content/uploads/2015/03/placeholder.gif"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 2,
                            Manager = "Chris Pommegranette",
                            Name = "Hammly Rangers",
                            Photo = "http://www.jennybeaumont.com/wp-content/uploads/2015/03/placeholder.gif"
                        },
                        new
                        {
                            Id = 6,
                            LeagueId = 2,
                            Manager = "Tom Potato",
                            Name = "Keebo United",
                            Photo = "http://www.jennybeaumont.com/wp-content/uploads/2015/03/placeholder.gif"
                        });
                });

            modelBuilder.Entity("FootballLeagueFinder.Models.Player", b =>
                {
                    b.HasOne("FootballLeagueFinder.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballLeagueFinder.Models.Team", b =>
                {
                    b.HasOne("FootballLeagueFinder.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootballLeagueFinder.Models.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballLeagueFinder.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
